config:
- MobileMonitoringTutorial: MobileMonitoringTutorial.json
- Test123: Test123.json
- TechTracker: TechTracker.json
- Te: Te.json
- TechTracker1: TechTracker1.json
MobileMonitoringTutorial:
- name: MobileMonitoringTutorial
Te:
- name: Te
TechTracker:
- name: TechTracker
TechTracker1:
- name: TechTracker (1)
Test123:
- name: Test123
